const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_TOKEN_MALFORMED: 'AUTH_004',
  AUTH_USER_NOT_FOUND: 'AUTH_005',
  AUTH_UNAUTHORIZED: 'AUTH_006',
  
  REG_EMAIL_EXISTS: 'REG_001',
  REG_USERNAME_EXISTS: 'REG_002',
  REG_PASSWORD_TOO_SHORT: 'REG_003',
  REG_EMAIL_INVALID: 'REG_004',
  
  LOGIN_USER_NOT_FOUND: 'LOGIN_001',
  LOGIN_WRONG_PASSWORD: 'LOGIN_002',
  
  GOAL_TITLE_EMPTY: 'GOAL_001',
  GOAL_TITLE_TOO_LONG: 'GOAL_002',
  GOAL_COLOR_INVALID: 'GOAL_003',
  GOAL_NOT_FOUND: 'GOAL_004',
  GOAL_NO_PERMISSION: 'GOAL_005',
  GOAL_DELETE_NO_PERMISSION: 'GOAL_006',
  
  DAY_DATE_INVALID: 'DAY_001',
  DAY_GOAL_NOT_FOUND: 'DAY_002',
  DAY_TIME_INVALID: 'DAY_004',
  DAY_NOT_FOUND: 'DAY_005',
  DAY_NO_PERMISSION: 'DAY_006',
  
  VALIDATION_REQUIRED: 'VAL_001',
  VALIDATION_FORMAT: 'VAL_002',
  VALIDATION_LENGTH: 'VAL_003',
  VALIDATION_RANGE: 'VAL_004',
  
  DB_READ_ERROR: 'DB_001',
  DB_WRITE_ERROR: 'DB_002',
  
  CORS_ORIGIN_NOT_ALLOWED: 'CORS_001',

  UNKNOWN_ERROR: 'UNKNOWN_001'
};

module.exports = {
  ErrorCodes
};
